export const resumeConstants = {
    UPSERT_REQUEST: 'RESUME_UPSERT_REQUEST',
    UPSERT_SUCCESS: 'RESUME_UPSERT_SUCCESS',
    UPSERT_FAILURE: 'RESUME_UPSERT_FAILURE',

    GET_RESUMES_REQUEST: 'GET_RESUMES_REQUEST',
    GET_RESUMES_SUCCESS: 'GET_RESUMES_SUCCESS',
    GET_RESUMES_FAILURE: 'GET_RESUMES_FAILURE',

    GET_RESUME_REQUEST: 'GET_RESUME_REQUEST',
    GET_RESUME_SUCCESS: 'GET_RESUME_SUCCESS',
    GET_RESUME_FAILURE: 'GET_RESUME_FAILURE',

    DELETE_REQUEST: 'RESUME_DELETE_REQUEST',
    DELETE_SUCCESS: 'RESUME_DELETE_SUCCESS',
    DELETE_FAILURE: 'RESUME_DELETE_FAILURE',
};
